baseURL = "https://20carbs.com/"
languageCode = "en-us"
title = "20 Carbs"
theme = "massively"
disqusShortname = "20carbs"
googleAnalytics = "UA-134043447-1"

# set below parameter to define a favicon
[params]
    favicon = "/favicon.png"
    author = "Fritzi Gandhi"
    site_description = "Healthy Keto Recipes Under 20 Carbs"
    description = "Healthy Keto Recipes Under 20 Carbs"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

# Below parameters can be set to override default post settings
[params.posts]
     foldername = "blog"
     pagesize = "10"
     featuredpost = "false"

[permalinks]
  blog = "/blog/:title/"

[taxonomies]
  category = "categories"

[languages]
[languages.en]
  languageName = "English"

